"""initial schema

Revision ID: 0001_initial
Revises:
Create Date: 2026-08-28

Hand-written rather than autogenerated (no live Postgres instance was
available to run `alembic revision --autogenerate` against while
building this) — it mirrors app/db/models.py exactly as of this
commit. If models.py changes, regenerate with:
    alembic revision --autogenerate -m "describe the change"
and review the output before applying, as always with autogenerate.
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001_initial"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.create_table(
        "evidence_clusters",
        sa.Column("cluster_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("member_report_ids", postgresql.JSONB, nullable=False),
        sa.Column("lat", sa.Float, nullable=False),
        sa.Column("lon", sa.Float, nullable=False),
        sa.Column("need_type", sa.String, nullable=False),
        sa.Column("people_affected_estimate", sa.Integer, nullable=True),
        sa.Column("reliability_score", sa.Float, nullable=False),
        sa.Column("confidence", sa.Float, nullable=False),
        sa.Column("contradictory", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("contradiction_notes", sa.Text, nullable=True),
        sa.Column("first_seen", sa.DateTime, nullable=False),
        sa.Column("last_seen", sa.DateTime, nullable=False),
        sa.Column("vulnerable_population", sa.Boolean, nullable=False, server_default=sa.false()),
        sa.Column("location_precision", sa.String, nullable=False, server_default="approximate"),
    )

    op.create_table(
        "reports",
        sa.Column("report_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("source", sa.String, nullable=False),
        sa.Column("source_reliability_hint", sa.Float, nullable=True),
        sa.Column("received_at", sa.DateTime, nullable=False),
        sa.Column("lat", sa.Float, nullable=False),
        sa.Column("lon", sa.Float, nullable=False),
        sa.Column("text", sa.Text, nullable=True),
        sa.Column("need_type", sa.String, nullable=False, server_default="unknown"),
        sa.Column("people_affected", sa.Integer, nullable=True),
        sa.Column("raw_payload", postgresql.JSONB, nullable=False),
        sa.Column("cluster_id", postgresql.UUID(as_uuid=True),
                   sa.ForeignKey("evidence_clusters.cluster_id"), nullable=True),
    )

    op.create_table(
        "mission_proposals",
        sa.Column("mission_id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("cluster_id", postgresql.UUID(as_uuid=True),
                   sa.ForeignKey("evidence_clusters.cluster_id"), nullable=False),
        sa.Column("supersedes_mission_id", postgresql.UUID(as_uuid=True),
                   sa.ForeignKey("mission_proposals.mission_id"), nullable=True),
        sa.Column("crew_id", sa.String, nullable=True),
        sa.Column("route_id", sa.String, nullable=True),
        sa.Column("supplies", postgresql.JSONB, nullable=False),
        sa.Column("priority_score", sa.Float, nullable=False),
        sa.Column("eta_minutes", sa.Float, nullable=True),
        sa.Column("assumptions", postgresql.JSONB, nullable=False),
        sa.Column("status", sa.String, nullable=False, server_default="proposed"),
        sa.Column("created_at", sa.DateTime, nullable=False),
    )

    op.create_table(
        "constraint_check_results",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("mission_id", postgresql.UUID(as_uuid=True),
                   sa.ForeignKey("mission_proposals.mission_id"), nullable=False),
        sa.Column("feasible", sa.Boolean, nullable=False),
        sa.Column("violations", postgresql.JSONB, nullable=False),
        sa.Column("fairness_note", sa.Text, nullable=True),
        sa.Column("checked_at", sa.DateTime, nullable=False),
    )

    op.create_table(
        "commander_decisions",
        sa.Column("id", postgresql.UUID(as_uuid=True), primary_key=True),
        sa.Column("mission_id", postgresql.UUID(as_uuid=True),
                   sa.ForeignKey("mission_proposals.mission_id"), nullable=False),
        sa.Column("decision", sa.String, nullable=False),
        sa.Column("modifications", postgresql.JSONB, nullable=True),
        sa.Column("decided_by", sa.String, nullable=False),
        sa.Column("decided_at", sa.DateTime, nullable=False),
    )

    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger, primary_key=True, autoincrement=True),
        sa.Column("client_event_id", sa.String, nullable=True, unique=True),
        sa.Column("source", sa.String, nullable=False),
        sa.Column("agent", sa.String, nullable=True),
        sa.Column("event_type", sa.String, nullable=False),
        sa.Column("entity_type", sa.String, nullable=True),
        sa.Column("entity_id", sa.String, nullable=True),
        sa.Column("context", postgresql.JSONB, nullable=False),
        sa.Column("level", sa.String, nullable=True),
        sa.Column("occurred_at", sa.DateTime, nullable=False),
        sa.Column("recorded_at", sa.DateTime, nullable=False),
    )
    op.create_index("ix_events_client_event_id", "events", ["client_event_id"])


def downgrade() -> None:
    op.drop_index("ix_events_client_event_id", table_name="events")
    op.drop_table("events")
    op.drop_table("commander_decisions")
    op.drop_table("constraint_check_results")
    op.drop_table("mission_proposals")
    op.drop_table("reports")
    op.drop_table("evidence_clusters")
